### ISSUE TITLE
Feature: User can Sign Up / Create an account.

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/dndFuze#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Sign Up/Create an account by setting a Username and Password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This application will start at the Sign Up page. The user will have to fill out a form by providing a username and password then clicking the submit button to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-09 at 1 50 14 PM](https://user-images.githubusercontent.com/103021766/200949449-17a96c89-2ba3-474e-858c-9f8a25734372.png)
![Screenshot 2022-11-09 at 1 50 24 PM](https://user-images.githubusercontent.com/103021766/200949465-257bd868-608d-4e42-922b-7d84a5246c36.png)
![Screenshot 2022-11-09 at 1 50 35 PM](https://user-images.githubusercontent.com/103021766/200949473-0f2a9d8e-c1d4-4429-bcb6-1f77be1899de.png)
![Screenshot 2022-11-09 at 1 50 56 PM](https://user-images.githubusercontent.com/103021766/200949484-741c3009-6929-479d-a94f-77c66eb3ecc1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... create the initial setup of schema.sql file to create all needed tables for the database.
- [x] Update `data.sql` to ... have user data such as **userId**, **username**, and **hashedPassword** in the **users** table.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by sharon-tieu** [comment]
https://user-images.githubusercontent.com/103021766/201722267-d79d5355-9141-49ca-bdfb-b173a386d009.mov
