### ISSUE TITLE
Feature: User can Sign-In to their account.

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/dndFuze#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can Sign-In to their account by inputting their username and password data. This will query the database base to see if information that was inputted matches with any of the data in the table. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click Sign-In on the navigation bar and the view will switch to a sign-in form. User inputs their username and password data and then click the Submit button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-09 at 2 27 46 PM](https://user-images.githubusercontent.com/103021766/200955614-a3a3df8b-6ed7-4ec4-b313-5cad75fa0442.png)
![Screenshot 2022-11-09 at 2 27 56 PM](https://user-images.githubusercontent.com/103021766/200955643-6eddcc35-05ba-4389-b068-d05084591566.png)
![Screenshot 2022-11-09 at 2 28 04 PM](https://user-images.githu
![Screenshot 2022-11-09 at 2 28 19 PM](https://user-images.githubusercontent.com/103021766/200955731-a077997c-60c8-4cea-91fe-3fc26a52c071.png)
busercontent.com/103021766/200955674-18214680-5394-4f37-b0d6-165b358ff6d9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by sharon-tieu** [comment]
https://user-images.githubusercontent.com/103021766/201722818-ef37a1ea-ab59-49b0-91b5-8e74e7e6a05d.mov
